spring.application.name=fare-payment-service

server.port=8084

spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_fare_payment_db
spring.data.mongodb.database=ridelink_fare_payment_db

springdoc.swagger-ui.path=/swagger-ui.html