spring.application.name=payment-service

server.port=8084

spring.data.mongodb.uri=mongodb://localhost:27017/paymentdb
spring.data.mongodb.database=paymentdb
spring.data.mongodb.auto-index-creation=true

springdoc.swagger-ui.path=/swagger-ui.html

service.owner=Perera P.N.D (IT24104027)
