server.port=8081
spring.application.name=account-service

# Isolated MongoDB Database for Database-per-Service Architecture
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=accountdb
spring.data.mongodb.auto-index-creation=true

# Owner metadata
service.owner=Sasiru (IT24200741)
